server:
    error:
        include-message: always
        include-binding-errors: always

spring:
    jpa:
        hibernate:
            ddl-auto:  update
    datasource:
        url: jdbc:mysql://unitask-mysql.mysql.database.azure.com/impl
        username: TeamOneMySQL
        password: Un1taskerz
        driver-class-name: com.mysql.cj.jdbc.Driver
    mail:
        host: smtp.gmail.com
        port: 587
        username: unitask370@gmail.com
        password: dxecgnicicrgsosy
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    mvc:
        cors:
            allowed-origins: "https://uni-task-beta-front.vercel.app"
            allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
            allowed-headers: "*"
            allow-credentials: true
    jackson:
        serialization:
            fail-on-empty-beans: false
        default-property-inclusion: non_null

# App Properties
unitask:
    app:
        jwtSecret: "======================unitask=Spring==========================="
        jwtExpirationMs: 86400000

